"""add_department_menus

Revision ID: 057d0e1960cf
Revises: 927e937218ac
Create Date: 2026-03-01 00:48:35.889199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057d0e1960cf'
down_revision: Union[str, None] = '927e937218ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_menus',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('kino_kbn', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id', 'menu_id')
    )
    op.drop_index('ix_role_menus_menu_id', table_name='role_menus')
    op.drop_index('ix_user_menus_menu_id', table_name='user_menus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_menus_menu_id', 'user_menus', ['menu_id'], unique=False)
    op.create_index('ix_role_menus_menu_id', 'role_menus', ['menu_id'], unique=False)
    op.drop_table('department_menus')
    # ### end Alembic commands ###
