"""add break fields to attendances

Revision ID: 05d4971bc34d
Revises: 47696373217f
Create Date: 2026-02-10 15:41:14.115380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d4971bc34d'
down_revision: Union[str, None] = '47696373217f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('break_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendances', sa.Column('break_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'break_end')
    op.drop_column('attendances', 'break_start')
    # ### end Alembic commands ###
