"""add_rbac_and_menus

Revision ID: 08089f89ae62
Revises: b7c8d9e0f1a2
Create Date: 2026-02-28 10:48:50.169322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08089f89ae62'
down_revision: Union[str, None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=100), server_default='', nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required_resource', sa.String(length=100), nullable=True),
    sa.Column('required_action', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('kino_kbn', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('kino_kbn', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'resource', 'action')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_menus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('kino_kbn', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'menu_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_wiki_attachments_page_id'), 'wiki_attachments', ['page_id'], unique=False)
    op.drop_index('idx_wiki_categories_name', table_name='wiki_categories')
    op.create_unique_constraint(None, 'wiki_categories', ['name'])
    op.drop_index('idx_wiki_page_tags_tag_id', table_name='wiki_page_tags')
    op.drop_index('ix_wiki_page_task_items_page_id', table_name='wiki_page_task_items')
    op.drop_index('ix_wiki_page_task_items_task_item_id', table_name='wiki_page_task_items')
    op.drop_index('ix_wiki_page_tasks_unique', table_name='wiki_page_tasks', postgresql_where='(task_id IS NOT NULL)')
    op.drop_index('idx_wiki_pages_author_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_category_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_parent_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_slug', table_name='wiki_pages')
    op.create_index(op.f('ix_wiki_pages_author_id'), 'wiki_pages', ['author_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_category_id'), 'wiki_pages', ['category_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_parent_id'), 'wiki_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_slug'), 'wiki_pages', ['slug'], unique=True)
    op.drop_index('idx_wiki_tags_name', table_name='wiki_tags')
    op.drop_index('idx_wiki_tags_slug', table_name='wiki_tags')
    op.create_index(op.f('ix_wiki_tags_slug'), 'wiki_tags', ['slug'], unique=True)
    op.create_unique_constraint(None, 'wiki_tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wiki_tags', type_='unique')
    op.drop_index(op.f('ix_wiki_tags_slug'), table_name='wiki_tags')
    op.create_index('idx_wiki_tags_slug', 'wiki_tags', ['slug'], unique=True)
    op.create_index('idx_wiki_tags_name', 'wiki_tags', ['name'], unique=True)
    op.drop_index(op.f('ix_wiki_pages_slug'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_parent_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_category_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_author_id'), table_name='wiki_pages')
    op.create_index('idx_wiki_pages_slug', 'wiki_pages', ['slug'], unique=True)
    op.create_index('idx_wiki_pages_parent_id', 'wiki_pages', ['parent_id'], unique=False)
    op.create_index('idx_wiki_pages_category_id', 'wiki_pages', ['category_id'], unique=False)
    op.create_index('idx_wiki_pages_author_id', 'wiki_pages', ['author_id'], unique=False)
    op.create_index('ix_wiki_page_tasks_unique', 'wiki_page_tasks', ['page_id', 'task_id'], unique=True, postgresql_where='(task_id IS NOT NULL)')
    op.create_index('ix_wiki_page_task_items_task_item_id', 'wiki_page_task_items', ['task_item_id'], unique=False)
    op.create_index('ix_wiki_page_task_items_page_id', 'wiki_page_task_items', ['page_id'], unique=False)
    op.create_index('idx_wiki_page_tags_tag_id', 'wiki_page_tags', ['tag_id'], unique=False)
    op.drop_constraint(None, 'wiki_categories', type_='unique')
    op.create_index('idx_wiki_categories_name', 'wiki_categories', ['name'], unique=True)
    op.drop_index(op.f('ix_wiki_attachments_page_id'), table_name='wiki_attachments')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('user_menus')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('role_menus')
    op.drop_table('roles')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
