"""add_log_source_alert_on_change

Revision ID: 0d0894c74444
Revises: b8f2a1c3d4e5
Create Date: 2026-02-18 09:25:56.642763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0894c74444'
down_revision: Union[str, None] = 'b8f2a1c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_sources', sa.Column('alert_on_change', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_sources', 'alert_on_change')
    # ### end Alembic commands ###
