"""add_backlog_ticket_id_to_daily_reports

Revision ID: 2509bc83417f
Revises: c1a2b3d4e5f6
Create Date: 2026-02-18 19:48:03.302207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2509bc83417f'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('backlog_ticket_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'backlog_ticket_id')
    # ### end Alembic commands ###
