"""add_calendar_rooms_and_room_id

Revision ID: 3b21411eef32
Revises: fe250895e6da
Create Date: 2026-02-11 15:34:30.036471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b21411eef32'
down_revision: Union[str, None] = 'fe250895e6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('calendar_events', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calendar_events_room_id'), 'calendar_events', ['room_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'calendar_rooms', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_room_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'room_id')
    op.drop_table('calendar_rooms')
    # ### end Alembic commands ###
