"""log_collection_v2_redesign

Revision ID: 3c7419e092cb
Revises: a5dceaeb239f
Create Date: 2026-02-18 04:28:06.101209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c7419e092cb'
down_revision: Union[str, None] = 'a5dceaeb239f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_line', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['log_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'file_name', name='uq_log_files_source_file')
    )
    op.create_index(op.f('ix_log_files_source_id'), 'log_files', ['source_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='INFO', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['log_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_file_id'), 'log_entries', ['file_id'], unique=False)
    op.create_index('ix_log_entries_file_line', 'log_entries', ['file_id', 'line_number'], unique=False)
    op.create_index('ix_log_entries_received_at', 'log_entries', ['received_at'], unique=False)
    op.add_column('log_sources', sa.Column('server_name', sa.String(length=200), nullable=False))
    op.add_column('log_sources', sa.Column('access_method', sa.String(length=10), nullable=False))
    op.add_column('log_sources', sa.Column('host', sa.String(length=255), nullable=False))
    op.add_column('log_sources', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('log_sources', sa.Column('username', sa.String(length=500), nullable=False))
    op.add_column('log_sources', sa.Column('password', sa.String(length=500), nullable=False))
    op.add_column('log_sources', sa.Column('domain', sa.String(length=200), nullable=True))
    op.add_column('log_sources', sa.Column('base_path', sa.String(length=1000), nullable=False))
    op.add_column('log_sources', sa.Column('file_pattern', sa.String(length=200), server_default='*.log', nullable=False))
    op.add_column('log_sources', sa.Column('encoding', sa.String(length=20), server_default='utf-8', nullable=False))
    op.add_column('log_sources', sa.Column('source_type', sa.String(length=20), server_default='OTHER', nullable=False))
    op.add_column('log_sources', sa.Column('collection_mode', sa.String(length=20), server_default='metadata_only', nullable=False))
    op.add_column('log_sources', sa.Column('consecutive_errors', sa.Integer(), nullable=False))
    op.add_column('log_sources', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('log_sources', 'last_collected_at')
    op.drop_column('log_sources', 'last_read_position')
    op.drop_column('log_sources', 'system_name')
    op.drop_column('log_sources', 'log_type')
    op.drop_column('log_sources', 'last_file_size')
    op.drop_column('log_sources', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_sources', sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('log_sources', sa.Column('last_file_size', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('log_sources', sa.Column('log_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('log_sources', sa.Column('system_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('log_sources', sa.Column('last_read_position', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('log_sources', sa.Column('last_collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('log_sources', 'last_checked_at')
    op.drop_column('log_sources', 'consecutive_errors')
    op.drop_column('log_sources', 'collection_mode')
    op.drop_column('log_sources', 'source_type')
    op.drop_column('log_sources', 'encoding')
    op.drop_column('log_sources', 'file_pattern')
    op.drop_column('log_sources', 'base_path')
    op.drop_column('log_sources', 'domain')
    op.drop_column('log_sources', 'password')
    op.drop_column('log_sources', 'username')
    op.drop_column('log_sources', 'port')
    op.drop_column('log_sources', 'host')
    op.drop_column('log_sources', 'access_method')
    op.drop_column('log_sources', 'server_name')
    op.drop_index('ix_log_entries_received_at', table_name='log_entries')
    op.drop_index('ix_log_entries_file_line', table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_file_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_log_files_source_id'), table_name='log_files')
    op.drop_table('log_files')
    # ### end Alembic commands ###
