"""add attendance_presets and user default_preset_id

Revision ID: 620335984593
Revises: 05d4971bc34d
Create Date: 2026-02-10 16:33:33.830540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620335984593'
down_revision: Union[str, None] = '05d4971bc34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('clock_in', sa.String(length=5), nullable=False),
    sa.Column('clock_out', sa.String(length=5), nullable=False),
    sa.Column('break_start', sa.String(length=5), nullable=True),
    sa.Column('break_end', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('default_preset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'attendance_presets', ['default_preset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_preset_id')
    op.drop_table('attendance_presets')
    # ### end Alembic commands ###
