"""add_unique_constraint_attendances_user_date

Revision ID: 6ddf43a20423
Revises: 2509bc83417f
Create Date: 2026-02-18 20:46:15.145449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddf43a20423'
down_revision: Union[str, None] = '2509bc83417f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendances_user_id_date', 'attendances', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendances_user_id_date', 'attendances', type_='unique')
    # ### end Alembic commands ###
