"""add log_sources table

Revision ID: 6ee8442a6984
Revises: c3790ffa7e38
Create Date: 2026-02-10 07:51:59.384840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee8442a6984'
down_revision: Union[str, None] = 'c3790ffa7e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('log_type', sa.String(length=100), nullable=False),
    sa.Column('parser_pattern', sa.Text(), nullable=True),
    sa.Column('severity_field', sa.String(length=100), nullable=True),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('polling_interval_sec', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_read_position', sa.BigInteger(), nullable=False),
    sa.Column('last_file_size', sa.BigInteger(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_sources')
    # ### end Alembic commands ###
