"""add visibility to todos

Revision ID: 86da56d0b359
Revises: 7e3eabbd85e8
Create Date: 2026-02-10 06:40:04.358972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da56d0b359'
down_revision: Union[str, None] = '7e3eabbd85e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'visibility')
    # ### end Alembic commands ###
