"""add_departments_table

Revision ID: 8868b471d6cb
Revises: 4671c277afb4
Create Date: 2026-02-27 22:07:59.323858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8868b471d6cb'
down_revision: Union[str, None] = '4671c277afb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_wiki_attachments_page_id'), 'wiki_attachments', ['page_id'], unique=False)
    op.drop_index('idx_wiki_categories_name', table_name='wiki_categories')
    op.create_unique_constraint(None, 'wiki_categories', ['name'])
    op.drop_index('idx_wiki_page_tags_tag_id', table_name='wiki_page_tags')
    op.drop_index('ix_wiki_page_task_items_page_id', table_name='wiki_page_task_items')
    op.drop_index('ix_wiki_page_task_items_task_item_id', table_name='wiki_page_task_items')
    op.drop_index('ix_wiki_page_tasks_unique', table_name='wiki_page_tasks', postgresql_where='(task_id IS NOT NULL)')
    op.drop_index('idx_wiki_pages_author_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_category_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_parent_id', table_name='wiki_pages')
    op.drop_index('idx_wiki_pages_slug', table_name='wiki_pages')
    op.create_index(op.f('ix_wiki_pages_author_id'), 'wiki_pages', ['author_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_category_id'), 'wiki_pages', ['category_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_parent_id'), 'wiki_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_slug'), 'wiki_pages', ['slug'], unique=True)
    op.drop_index('idx_wiki_tags_name', table_name='wiki_tags')
    op.drop_index('idx_wiki_tags_slug', table_name='wiki_tags')
    op.create_index(op.f('ix_wiki_tags_slug'), 'wiki_tags', ['slug'], unique=True)
    op.create_unique_constraint(None, 'wiki_tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wiki_tags', type_='unique')
    op.drop_index(op.f('ix_wiki_tags_slug'), table_name='wiki_tags')
    op.create_index('idx_wiki_tags_slug', 'wiki_tags', ['slug'], unique=True)
    op.create_index('idx_wiki_tags_name', 'wiki_tags', ['name'], unique=True)
    op.drop_index(op.f('ix_wiki_pages_slug'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_parent_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_category_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_author_id'), table_name='wiki_pages')
    op.create_index('idx_wiki_pages_slug', 'wiki_pages', ['slug'], unique=True)
    op.create_index('idx_wiki_pages_parent_id', 'wiki_pages', ['parent_id'], unique=False)
    op.create_index('idx_wiki_pages_category_id', 'wiki_pages', ['category_id'], unique=False)
    op.create_index('idx_wiki_pages_author_id', 'wiki_pages', ['author_id'], unique=False)
    op.create_index('ix_wiki_page_tasks_unique', 'wiki_page_tasks', ['page_id', 'task_id'], unique=True, postgresql_where='(task_id IS NOT NULL)')
    op.create_index('ix_wiki_page_task_items_task_item_id', 'wiki_page_task_items', ['task_item_id'], unique=False)
    op.create_index('ix_wiki_page_task_items_page_id', 'wiki_page_task_items', ['page_id'], unique=False)
    op.create_index('idx_wiki_page_tags_tag_id', 'wiki_page_tags', ['tag_id'], unique=False)
    op.drop_constraint(None, 'wiki_categories', type_='unique')
    op.create_index('idx_wiki_categories_name', 'wiki_categories', ['name'], unique=True)
    op.drop_index(op.f('ix_wiki_attachments_page_id'), table_name='wiki_attachments')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
