"""add_user_preferred_locale

Revision ID: a5dceaeb239f
Revises: a943bf44ce3b
Create Date: 2026-02-17 16:16:14.354060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dceaeb239f'
down_revision: Union[str, None] = 'a943bf44ce3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_locale', sa.String(length=10), server_default='ja', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_locale')
    # ### end Alembic commands ###
