"""add report to tasks

Revision ID: d58961695bbb
Revises: e3a82a9fcd2f
Create Date: 2026-02-10 18:01:36.445539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58961695bbb'
down_revision: Union[str, None] = 'e3a82a9fcd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('tasks', sa.Column('report', sa.Boolean(), server_default=sa.text('false'), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'report')
    # ### end Alembic commands ###
