"""add_department_menus_menu_id_index

Revision ID: de30cd662868
Revises: 057d0e1960cf
Create Date: 2026-03-01 10:32:20.844340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de30cd662868'
down_revision: Union[str, None] = '057d0e1960cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_department_menus_menu_id'), 'department_menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_role_menus_menu_id'), 'role_menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_user_menus_menu_id'), 'user_menus', ['menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_menus_menu_id'), table_name='user_menus')
    op.drop_index(op.f('ix_role_menus_menu_id'), table_name='role_menus')
    op.drop_index(op.f('ix_department_menus_menu_id'), table_name='department_menus')
    # ### end Alembic commands ###
