"""remove daily_report unique constraint

Revision ID: e3a82a9fcd2f
Revises: a1b2c3d4e5f6
Create Date: 2026-02-10 18:00:56.015447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a82a9fcd2f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_report_date', 'daily_reports', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_report_date', 'daily_reports', ['user_id', 'report_date'])
    # ### end Alembic commands ###
