"""add input_type to attendances

Revision ID: fa32f8e03649
Revises: 620335984593
Create Date: 2026-02-10 16:56:34.541629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa32f8e03649'
down_revision: Union[str, None] = '620335984593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('input_type', sa.String(length=10), server_default='web', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'input_type')
    # ### end Alembic commands ###
