"""add_calendar_tables

Revision ID: fe250895e6da
Revises: 4f88001d4f7c
Create Date: 2026-02-11 14:41:52.313504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe250895e6da'
down_revision: Union[str, None] = '4f88001d4f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('recurrence_end', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_creator_id'), 'calendar_events', ['creator_id'], unique=False)
    op.create_table('user_calendar_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_color', sa.String(length=7), nullable=False),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('default_reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('show_task_list', sa.Boolean(), nullable=False),
    sa.Column('show_attendance', sa.Boolean(), nullable=False),
    sa.Column('show_reports', sa.Boolean(), nullable=False),
    sa.Column('working_hours_start', sa.String(length=5), nullable=False),
    sa.Column('working_hours_end', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('calendar_event_attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_attendee')
    )
    op.create_index(op.f('ix_calendar_event_attendees_event_id'), 'calendar_event_attendees', ['event_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_attendees_user_id'), 'calendar_event_attendees', ['user_id'], unique=False)
    op.create_table('calendar_event_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_event_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('override_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['override_event_id'], ['calendar_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('minutes_before', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_pending', 'calendar_reminders', ['remind_at', 'is_sent'], unique=False)
    op.alter_column('tasks', 'report',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'report',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_reminders_pending', table_name='calendar_reminders')
    op.drop_table('calendar_reminders')
    op.drop_table('calendar_event_exceptions')
    op.drop_index(op.f('ix_calendar_event_attendees_user_id'), table_name='calendar_event_attendees')
    op.drop_index(op.f('ix_calendar_event_attendees_event_id'), table_name='calendar_event_attendees')
    op.drop_table('calendar_event_attendees')
    op.drop_table('user_calendar_settings')
    op.drop_index(op.f('ix_calendar_events_creator_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
